name: Go Build and Artifacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # بنجرب على نسختين عشان نضمن إن الكود شغال صح (Matrix)
        go-version: [ '1.20', '1.21.x' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        # السيرفر هو اللي هيعمل tidy مش جهازك
        run: go mod tidy

      - name: Build
        # بناء البرنامج وتسميته
        run: go build -v -o myproject

      - name: Upload Binary
        # رفع الملف الناتج عشان تقدر تحمله من موقع جيت هاب
        uses: actions/upload-artifact@v4
        with:
          name: binary-go-${{ matrix.go-version }}
          path: myproject